create extension if not exists moddatetime schema extensions;

alter table if exists public.site_settings
  add column if not exists whatsapp_number text,
  add column if not exists hall_price integer not null default 30000,
  add column if not exists room_price integer not null default 1500,
  add column if not exists hall_price_4hrs numeric default 30000,
  add column if not exists room_price_night numeric default 1500,
  add column if not exists room_count integer not null default 4,
  add column if not exists location_label text not null default 'Allapra, Perumbavoor',
  add column if not exists address_line_1 text not null default 'First Floor, Diamond Arcade, Allapra P.O,',
  add column if not exists address_line_2 text not null default 'Perumbavoor, Ernakulam, Kerala 683556',
  add column if not exists map_label text not null default 'Diamond Arcade, Allapra P.O, Perumbavoor',
  add column if not exists inquiry_hours text not null default 'Open for inquiries 9 AM – 9 PM, all days',
  add column if not exists seo_description text default 'Luxury AC banquet hall in Allapra, Perumbavoor.',
  add column if not exists seo_keywords text default 'banquet hall perumbavoor, wedding hall allapra';

insert into public.site_settings (
  id,
  hall_name,
  contact_number,
  instagram_handle,
  google_maps_link,
  whatsapp_number,
  hall_price,
  room_price,
  room_count,
  location_label,
  address_line_1,
  address_line_2,
  map_label,
  inquiry_hours
)
values (
  1,
  'Diamond Banquet Hall',
  '9947681202',
  '@diamondhallallapra',
  'https://maps.app.goo.gl/vZWrqc6f6b9hvNj88',
  '919947681202',
  30000,
  1500,
  4,
  'Allapra, Perumbavoor',
  'First Floor, Diamond Arcade, Allapra P.O,',
  'Perumbavoor, Ernakulam, Kerala 683556',
  'Diamond Arcade, Allapra P.O, Perumbavoor',
  'Open for inquiries 9 AM – 9 PM, all days'
)
on conflict (id) do nothing;

update public.site_settings
set
  whatsapp_number = coalesce(whatsapp_number, '919947681202'),
  hall_price = coalesce(hall_price, 30000),
  room_price = coalesce(room_price, 1500),
  hall_price_4hrs = coalesce(hall_price_4hrs, hall_price, 30000),
  room_price_night = coalesce(room_price_night, room_price, 1500),
  room_count = coalesce(room_count, 4),
  location_label = coalesce(location_label, 'Allapra, Perumbavoor'),
  address_line_1 = coalesce(address_line_1, 'First Floor, Diamond Arcade, Allapra P.O,'),
  address_line_2 = coalesce(address_line_2, 'Perumbavoor, Ernakulam, Kerala 683556'),
  map_label = coalesce(map_label, 'Diamond Arcade, Allapra P.O, Perumbavoor'),
  inquiry_hours = coalesce(inquiry_hours, 'Open for inquiries 9 AM – 9 PM, all days'),
  seo_description = coalesce(seo_description, 'Luxury AC banquet hall in Allapra, Perumbavoor.'),
  seo_keywords = coalesce(seo_keywords, 'banquet hall perumbavoor, wedding hall allapra')
where id = 1;

create unique index if not exists bookings_booked_date_key
on public.bookings (booked_date);

alter table public.bookings enable row level security;

drop policy if exists "Public read bookings" on public.bookings;
create policy "Public read bookings"
on public.bookings
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated manage bookings" on public.bookings;
create policy "Authenticated manage bookings"
on public.bookings
for all
to authenticated
using (true)
with check (true);

alter table public.site_settings enable row level security;

drop policy if exists "Public read site settings" on public.site_settings;
create policy "Public read site settings"
on public.site_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated manage site settings" on public.site_settings;
create policy "Authenticated manage site settings"
on public.site_settings
for all
to authenticated
using (id = 1)
with check (id = 1);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  reviewer_name text,
  event_type text not null,
  date_label text not null,
  event_date text,
  review_text text not null,
  is_visible boolean default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.reviews
  add column if not exists reviewer_name text,
  add column if not exists event_date text,
  add column if not exists is_visible boolean default true,
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

update public.reviews
set
  reviewer_name = coalesce(reviewer_name, name),
  event_date = coalesce(event_date, date_label),
  is_visible = coalesce(is_visible, true),
  updated_at = coalesce(updated_at, created_at, timezone('utc', now()));

insert into public.reviews (name, event_type, date_label, review_text)
values
  ('Rajan & Priya', 'Wedding', 'March 2025', 'The hall was stunning and the staff were so helpful throughout. Our wedding day was perfect. Highly recommend Diamond Banquet Hall to everyone in Perumbavoor.'),
  ('Suresh Nair', 'Reception', 'January 2025', 'Excellent venue, very well maintained and spacious. The valet parking was smooth and all our guests were impressed. Will definitely book again.'),
  ('Anjali Thomas', 'Engagement', 'November 2024', 'Beautiful hall, affordable price, and wonderful service. The rooms were clean and comfortable for our out-of-town guests. Truly a premium experience.'),
  ('Mohammed Rashid', 'Birthday Celebration', 'October 2024', 'Booked for my daughter''s birthday. The team was cooperative and flexible. Decor came out beautifully in this space. Very happy with the overall experience.'),
  ('Lekha & Arun', 'Wedding', 'September 2024', 'From the first enquiry to the final day, everything was seamless. The hall looked absolutely royal. Our guests could not stop complimenting the venue.')
on conflict do nothing;

alter table public.reviews enable row level security;

drop policy if exists "Public read reviews" on public.reviews;
create policy "Public read reviews"
on public.reviews
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated manage reviews" on public.reviews;
create policy "Authenticated manage reviews"
on public.reviews
for all
to authenticated
using (true)
with check (true);

drop trigger if exists handle_reviews_updated_at on public.reviews;
create trigger handle_reviews_updated_at
before update on public.reviews
for each row
execute procedure extensions.moddatetime(updated_at);

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  event_date date,
  message text,
  status text default 'new' check (status in ('new', 'contacted', 'booked', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.enquiries enable row level security;

drop policy if exists "Public can submit enquiries" on public.enquiries;
create policy "Public can submit enquiries"
on public.enquiries
for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins manage enquiries" on public.enquiries;
create policy "Admins manage enquiries"
on public.enquiries
for all
to authenticated
using (true)
with check (true);
